import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "next-themes";
import "./globals.css";
import BootstrapClient from "@/components/BootstrapClient";
import AppNavbar from '@/components/Navbar';
import Footer from '@/components/Footer';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} d-flex flex-column`}>
        <ThemeProvider attribute="data-bs-theme" defaultTheme="system" enableSystem disableTransitionOnChange>
          <AppNavbar />
          <main className="mt-4 flex-grow-1 container mt-4">{children}</main>
          <Footer />
        </ThemeProvider>
        <BootstrapClient />
      </body>
    </html>
  );
}
